version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:6.2-alpine

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
      - MYSQL_DATABASE=go-lib-backend
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    build: .

    command: bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh db:3306 --timeout=30 --strict -- python3 db_init.py && python3 main.py"
#    command: bash -c "python3 main.py"
    # command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  
  celery:
    container_name: celery
    build: .
    command: bash -c "celery -A my_celery worker -l INFO"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - backend


  
      