version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DBPASSWORD}
      - MYSQL_DATABASE=go-lib-backend
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    build: .
    restart: always
    command: bash -c "python3 -u setup.py main"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

    



  
      