version: '3.8'

services:
  booker:
    container_name: booker
    build: .
    restart: always
    command: bash -c "python3 -u setup.py booker --host ${DB_HOST} --worker_size ${WORKER_SIZE} --worker_id ${WORKER_ID}"
    volumes:
      - .:/app

  pool:
    container_name: pool
    build: .
    restart: always
    command: bash -c "python3 -u setup.py pool --host ${DB_HOST}"
    volumes:
      - .:/app
  
  cancel:
    container_name: cancel
    build: .
    restart: always
    command: bash -c "python3 -u setup.py cancel --host ${DB_HOST}"
    volumes:
      - .:/app
  
