version: '3.8'

services:
  booker:
    container_name: booker
    build: .
    restart: always
    command: bash -c "python3 -u book_main.py ${DB_HOST} ${BOOKER_SIZE} ${BOOKER_ID}"
    volumes:
      - .:/app
