version: '3.8'

services:
  pool:
    container_name: pool
    build: .
    restart: always
    command: bash -c "python3 -u setup.py pool --host ${DB_HOST}"
    volumes:
      - .:/app

  cancel:
    container_name: cancel
    build: .
    restart: always
    command: bash -c "python3 -u setup.py cancel --host ${DB_HOST}"
    volumes:
      - .:/app