version: '3.8'

services:
  booker:
    container_name: booker
    build: .
    restart: always
    command: bash -c "python3 -u setup.py booker --host ${DB_HOST} --worker_size ${WORKER_SIZE} --worker_id ${WORKER_ID}"
    volumes:
      - .:/app

  
